/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoiDungRouteImport } from './routes/noi-dung'
import { Route as QuanLyGiaiRouteImport } from './routes/quan-ly-giai'
import { Route as VanDongVienRouteImport } from './routes/van-dong-vien'
import { Route as ChamDiemMatchIdRouteImport } from './routes/cham-diem.$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoiDungRoute = NoiDungRouteImport.update({
  id: '/noi-dung',
  path: '/noi-dung',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyGiaiRoute = QuanLyGiaiRouteImport.update({
  id: '/quan-ly-giai',
  path: '/quan-ly-giai',
  getParentRoute: () => rootRouteImport,
} as any)
const VanDongVienRoute = VanDongVienRouteImport.update({
  id: '/van-dong-vien',
  path: '/van-dong-vien',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamDiemMatchIdRoute = ChamDiemMatchIdRouteImport.update({
  id: '/cham-diem/$matchId',
  path: '/cham-diem/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/noi-dung': typeof NoiDungRoute
  '/quan-ly-giai': typeof QuanLyGiaiRoute
  '/van-dong-vien': typeof VanDongVienRoute
  '/cham-diem/$matchId': typeof ChamDiemMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/noi-dung': typeof NoiDungRoute
  '/quan-ly-giai': typeof QuanLyGiaiRoute
  '/van-dong-vien': typeof VanDongVienRoute
  '/cham-diem/$matchId': typeof ChamDiemMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/noi-dung': typeof NoiDungRoute
  '/quan-ly-giai': typeof QuanLyGiaiRoute
  '/van-dong-vien': typeof VanDongVienRoute
  '/cham-diem/$matchId': typeof ChamDiemMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/noi-dung'
    | '/quan-ly-giai'
    | '/van-dong-vien'
    | '/cham-diem/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/noi-dung'
    | '/quan-ly-giai'
    | '/van-dong-vien'
    | '/cham-diem/$matchId'
  id:
    | '__root__'
    | '/'
    | '/noi-dung'
    | '/quan-ly-giai'
    | '/van-dong-vien'
    | '/cham-diem/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoiDungRoute: typeof NoiDungRoute
  QuanLyGiaiRoute: typeof QuanLyGiaiRoute
  VanDongVienRoute: typeof VanDongVienRoute
  ChamDiemMatchIdRoute: typeof ChamDiemMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noi-dung': {
      id: '/noi-dung'
      path: '/noi-dung'
      fullPath: '/noi-dung'
      preLoaderRoute: typeof NoiDungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly-giai': {
      id: '/quan-ly-giai'
      path: '/quan-ly-giai'
      fullPath: '/quan-ly-giai'
      preLoaderRoute: typeof QuanLyGiaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/van-dong-vien': {
      id: '/van-dong-vien'
      path: '/van-dong-vien'
      fullPath: '/van-dong-vien'
      preLoaderRoute: typeof VanDongVienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cham-diem/$matchId': {
      id: '/cham-diem/$matchId'
      path: '/cham-diem/$matchId'
      fullPath: '/cham-diem/$matchId'
      preLoaderRoute: typeof ChamDiemMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoiDungRoute: NoiDungRoute,
  QuanLyGiaiRoute: QuanLyGiaiRoute,
  VanDongVienRoute: VanDongVienRoute,
  ChamDiemMatchIdRoute: ChamDiemMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
