/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BangTySoRouteImport } from './routes/bang-ty-so'
import { Route as NoiDungRouteImport } from './routes/noi-dung'
import { Route as QuanLyDoiRouteImport } from './routes/quan-ly-doi'
import { Route as TheThucRouteImport } from './routes/the-thuc'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BangTySoRoute = BangTySoRouteImport.update({
  id: '/bang-ty-so',
  path: '/bang-ty-so',
  getParentRoute: () => rootRouteImport,
} as any)
const NoiDungRoute = NoiDungRouteImport.update({
  id: '/noi-dung',
  path: '/noi-dung',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyDoiRoute = QuanLyDoiRouteImport.update({
  id: '/quan-ly-doi',
  path: '/quan-ly-doi',
  getParentRoute: () => rootRouteImport,
} as any)
const TheThucRoute = TheThucRouteImport.update({
  id: '/the-thuc',
  path: '/the-thuc',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bang-ty-so': typeof BangTySoRoute
  '/noi-dung': typeof NoiDungRoute
  '/quan-ly-doi': typeof QuanLyDoiRoute
  '/the-thuc': typeof TheThucRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bang-ty-so': typeof BangTySoRoute
  '/noi-dung': typeof NoiDungRoute
  '/quan-ly-doi': typeof QuanLyDoiRoute
  '/the-thuc': typeof TheThucRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bang-ty-so': typeof BangTySoRoute
  '/noi-dung': typeof NoiDungRoute
  '/quan-ly-doi': typeof QuanLyDoiRoute
  '/the-thuc': typeof TheThucRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bang-ty-so' | '/noi-dung' | '/quan-ly-doi' | '/the-thuc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bang-ty-so' | '/noi-dung' | '/quan-ly-doi' | '/the-thuc'
  id:
    | '__root__'
    | '/'
    | '/bang-ty-so'
    | '/noi-dung'
    | '/quan-ly-doi'
    | '/the-thuc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BangTySoRoute: typeof BangTySoRoute
  NoiDungRoute: typeof NoiDungRoute
  QuanLyDoiRoute: typeof QuanLyDoiRoute
  TheThucRoute: typeof TheThucRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bang-ty-so': {
      id: '/bang-ty-so'
      path: '/bang-ty-so'
      fullPath: '/bang-ty-so'
      preLoaderRoute: typeof BangTySoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noi-dung': {
      id: '/noi-dung'
      path: '/noi-dung'
      fullPath: '/noi-dung'
      preLoaderRoute: typeof NoiDungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly-doi': {
      id: '/quan-ly-doi'
      path: '/quan-ly-doi'
      fullPath: '/quan-ly-doi'
      preLoaderRoute: typeof QuanLyDoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-thuc': {
      id: '/the-thuc'
      path: '/the-thuc'
      fullPath: '/the-thuc'
      preLoaderRoute: typeof TheThucRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BangTySoRoute: BangTySoRoute,
  NoiDungRoute: NoiDungRoute,
  QuanLyDoiRoute: QuanLyDoiRoute,
  TheThucRoute: TheThucRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
